name: PE
version: 0.0.1-BETA
main: dev.nuer.pe.PE
author: Nuer
api-version: 1.13
commands:
  pe:
    usage: /<command>
    description: main command for PE, use '/pe help' for command help
  ce:
    usage: /<command>
    description: main command for PE, use '/pe help' for command help
  enchanter:
    usage: /<command>
    description: main command for PE, use '/pe help' for command help